apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: "TCP"
      port: 2020 # The port that the service is running on in the cluster
      targetPort: 2020 # The port exposed by the service
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-service
    spec:
      containers:
      - image: shubhamdhama10/product-service
        name: product-service
        ports:
        - containerPort: 2020
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: password
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: username
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: port
         